# This workflow runs when new change is pushed to repo OR when a new PR is created
# It performs all of the tests to make sure everything is good.

---
name: PR Runner

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 游닌 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Lint
        run: yarn ci:lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 游닌 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Build
        run: yarn ci:build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 游닌 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Run tests
        run: yarn ci:test --verbose

  site:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 游닌 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Build Site
        run: yarn g:nx build @builder.io/mitosis-site

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 游닌 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Build
        run: yarn ci:build --verbose

      - name: Run E2E tests
        run: yarn ci:e2e --verbose
